
# Copyright (c) 2024-2026 TaskForge Team
# SPDX-License-Identifier: BSL-1.1

"""自动文档水印配置 — P3: AI 输出审计追踪"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class WatermarkConfig(BaseModel):
    """自动文档水印配置 — P3: AI 输出审计追踪"""

    enabled: bool = Field(default=False, description="启用自动水印 (TF_WATERMARK__ENABLED)")
    mode: Literal["explicit", "hidden", "both"] = Field(default="explicit", description="水印模式 (TF_WATERMARK__MODE)")
    text: str = Field(default="Generated by TaskForge AI", max_length=200, description="水印文本 (TF_WATERMARK__TEXT)")
    font_path: str = Field(default="", description="水印字体路径 (TF_WATERMARK__FONT_PATH)")
    skip_extensions: list[str] = Field(
        default_factory=lambda: [
            ".mp4",
            ".avi",
            ".mov",
            ".mp3",
            ".wav",
            ".py",
            ".js",
            ".go",
            ".sh",
            ".json",
            ".xml",
            ".html",
        ],
        description="跳过的文件扩展名 (TF_WATERMARK__SKIP_EXTENSIONS)",
    )
    dedup_window_ms: int = Field(
        default=5000, ge=1000, le=60000, description="去重窗口(毫秒) (TF_WATERMARK__DEDUP_WINDOW_MS)"
    )
